# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='author',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='doi',
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AlterField(
            model_name='citation',
            name='isbn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='citation',
            name='journal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='publisher',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='citation',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
