# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 17:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('year', models.IntegerField()),
                ('sets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=17), size=None)),
                ('advisor', models.ManyToManyField(related_name='theses_advised', to='theses.Person')),
                ('author', models.ManyToManyField(related_name='theses_written', to='theses.Person')),
                ('department', models.ManyToManyField(to='theses.Department')),
            ],
        ),
    ]
