# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        # See https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#indexing-arrayfield .
        migrations.RunSQL('CREATE INDEX ON theses_thesis USING GIN (sets);')
    ]
