# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='degree',
            field=models.CharField(max_length=20),
        ),
    ]
