# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0002_auto_20171017_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='course',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
