# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0002_auto_20171023_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='thesis',
            name='title',
            field=models.TextField(),
        ),
    ]
