# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_auto_20171023_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='unextractable',
            field=models.BooleanField(default=False, help_text='Will be set to True if attempts to extract text from the pdf failed; such theses are not part of the neural net.'),
        ),
    ]
