# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0004_thesis_unextractable'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='_vector',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
