# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0005_thesis__vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='unextractable',
            field=models.BooleanField(default=False, help_text='Will be set to True if attempts to extract text from the pdf failed; such theses are not part of the neural net, and cannot be used in data visualization.'),
        ),
    ]
