# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0006_auto_20171120_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='_vector',
        ),
    ]
